import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Prime Ads Hub | Reporting", layout="wide")

# Custom CSS for Branding
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    </style>
    """, unsafe_allow_html=True)

st.title("🚀 Prime Ads Hub Branding & Reporting")
st.write("Real-time Ad Manager Insights (Auto-refreshed every 3 hours)")

# Load the data generated by the fetcher
@st.cache_data
def load_data():
    return pd.read_csv('gam_report_data.csv')

try:
    df = load_data()

    # --- TOP ROW: KPI CARDS ---
    col1, col2, col3, col4 = st.columns(4)
    total_rev = df['Net_Revenue'].sum()
    total_imps = df['Column.AD_SERVER_IMPRESSIONS'].sum()
    
    col1.metric("Total Net Revenue", f"${total_rev:,.2f}")
    col2.metric("Total Impressions", f"{total_imps:,}")
    col3.metric("Avg eCPM", f"${(total_rev/total_imps*1000):,.2;f}")
    col4.metric("Active Units", df['Dimension.AD_UNIT_NAME'].nunique())

    # --- MIDDLE ROW: CHARTS ---
    st.subheader("Revenue Performance")
    fig = px.area(df, x='Dimension.DATE', y='Net_Revenue', color='Dimension.AD_UNIT_NAME', 
                  title="Revenue by Ad Unit", template="plotly_white")
    st.plotly_chart(fig, use_container_width=True)

    # --- BOTTOM ROW: DATA TABLE ---
    st.subheader("Deep Dive Reporting")
    st.dataframe(df, use_container_width=True)

except FileNotFoundError:
    st.error("No data found. Please run the fetcher script first.")
